# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "caioh" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        r-version: ['release']

    steps:
      - uses: actions/checkout@v3

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install system dependencies
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
          sudo apt update
          sudo apt install r-cran-rgl r-cran-reticulate r-cran-keras r-cran-ggplot2 r-cran-viridis r-cran-lidr r-cran-caret r-cran-rcmdcheck r-cran-remotes
        shell: bash

      - name: List installed packages
        run: basename(list.dirs(.libPaths(), recursive = F))
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
